FROM node:22 AS builder
WORKDIR /build
COPY package*.json ./
RUN npm ci
COPY . ./

RUN npm run build

# Use a common base image to reduce the cold start time
FROM public.ecr.aws/lambda/nodejs:22

# Install Lambda Web Adapter
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.9.0 /lambda-adapter /opt/extensions/lambda-adapter
ENV PORT=3000

COPY --from=builder /build/next.config.ts ./
COPY --from=builder /build/public ./public
COPY --from=builder /build/.next/static ./.next/static
COPY --from=builder /build/.next/standalone ./

# Changes due to the base image
ENTRYPOINT ["node"]
CMD ["server.js"]
